### PR TITLE
Launch instructions for smbcmp-gui and search feature.

### PR DESCRIPTION
**Pull request by RMPR**

### CODE REVIEW

**Comment by aaptel** [comment]
Return now works but it still doesn't loop back :(

**Comment by RMPR** [comment]
Now the loop back works, it was a edge case, basically the function got stuck on the last packet.

**Comment by aaptel** [comment]
It's better but I still cannot reach the first summary by searching for it (e.g. with "req").

**Comment by RMPR** [comment]
Steps to reproduce ?

**Comment by aaptel** [comment]
Open capture `ok-enc-SMB3_00.pcap` from the samples you have. Type "req" in search box and hit enter twice or more times. Selection never goes to first summary despite it containing "request".

**Comment by RMPR** [comment]
This use case is now covered.

**Pull request merged**
